version: "3"
services:
  react-app:
    image: react-front
    stdin_open: true
    ports:
      - "4000:3000"
    networks:
      - mern-app
  api-server:
    image: exp-server
    ports:
      - "3001:3001"
    networks:
      - mern-app
    depends_on:
      - mongo
  mongo:
    image: mongo:5.0.8
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - mongodata:/data/db
    container_name: mongo_mongo
networks:
  mern-app:
    driver: bridge
volumes:
  mongodata:
    driver: local
